### ISSUE TITLE
数据集下载链接404了

### ISSUE THREAD

**Issue by silverriver** [opendatalab/WanJuan1.0#2]
https://github.com/opendatalab/WanJuan1.0
这个链接打开是404

**Comment by conghui** [comment]
数据集已经完成上架，重新访问即可：https://opendatalab.com/WanJuan1.0

**Comment by thesby** [comment]
@conghui 您好，https://opendatalab.com/WanJuan1.0 无法访问，404 了

**Comment by thesby** [comment]
地址变了 https://opendatalab.org.cn/OpenDataLab/WanJuan1_dot_0
