### ISSUE TITLE
关于断点续传

### ISSUE THREAD

**Issue by nuoma** [opendatalab/WanJuan1.0#8]
你好，我使用你们的CLI进行下载：odl get    WanJuan1.0/raw/nlp，无奈文件确实太大，我的网速无法保证能完整的下载，现在已经被QoS限速了，请问你们的工具能够断点续传吗？或者会不会提供一个百度网盘这种的链接，谢谢！

**Comment by waynesapphire** [comment]
支持断点续传的。
如果下载因为connection 或者其他原因断掉，重新执行一下下载命令就好了。下载过程中会生成一个.cache/ 文件夹，请不要对它进行操作。

**Comment by waynesapphire** [comment]
> 你好，我使用你们的CLI进行下载：odl get WanJuan1.0/raw/nlp，无奈文件确实太大，我的网速无法保证能完整的下载，现在已经被QoS限速了，请问你们的工具能够断点续传吗？或者会不会提供一个百度网盘这种的链接，谢谢！

支持断点续传的。
如果下载因为connection 或者其他原因断掉，重新执行一下下载命令就好了。下载过程中会生成一个.cache/ 文件夹，请不要对它进行操作

**Comment by nuoma** [comment]
谢谢，成功了。
